version: '3'
services:
  # prisma:
  #   image: prismagraphql/prisma:1.34
  #   restart: always
  #   ports:
  #     - '4466:4466'
  #   environment:
  #     PRISMA_CONFIG: |
  #       managementApiSecret: my-server-secret-123
  #       port: 4466
  #       databases:
  #         default:
  #           connector: mysql
  #           host: mysql-db
  #           port: 3306
  #           user: root
  #           password: prisma
  #           database: sq
  mysql-db:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: 'sq'
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: ~
